export const people = {
  jon: {
    "SQLAlchemy ORM": "none",
    Redux: "none",
    "Vanilla JS": "teach",
    "React16 (Hooks, Context)": "none",
    Python: "intermediate",
    "Front End Build Tools": "junior",
    "Feature Toggles": "none",
    "JS Testing": "intermediate",
    "Python Testing": "intermediate",
    "Production Monitoring": "advanced",
    "UI Design": "none",
    "Heart & Soul": "teach",
    PostgreSQL: "teach",
    git: "teach",
    Docker: "teach",
    "Build Pipelines": "advanced",
    Elixir: "advanced",
    Typescript: "teach",
    Swift: "intermediate",
    "Objective-C": "intermediate",
    Android: "none",
    "Apple App Store Pipeline": "none",
    MongoDB: "junior",
    "Python - Flask": "junior",
    "Python - Django": "intermediate",
    "Performance Profiling": "teach",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "intermediate",
    "TF - NLP": "none",
    "React Native": "none",
    "AWS S3": "teach",
    "AWS EC2": "teach",
    "AWS RDS": "teach",
    "AWS Amplify": "none",
    Netlify: "junior",
    Heroku: "teach",
    "Microsoft Azure": "none",
    Ruby: "teach",
    Erlang: "intermediate",
    "C#": "advanced",
    "Backbone/Marionette JS": "none",
    RabbitMQ: "intermediate",
    "AWS Lambda": "teach",
    Webflow: "none",
    CouchDB: "intermediate",
    Java: "advanced",
    "HTML / CSS": "advanced",
    "Postman API Development": "none",
    Node: "advanced",
    Vue: "none",
    Bootstrap: "junior",
    jQuery: "teach",
    SQL: "teach",
    "Bash/Powershell": "teach",
    Express: "intermediate",
    PHP: "junior",
    "C++": "advanced",
    C: "advanced",
    Go: "teach",
    Assembly: "intermediate",
    Kotlin: "intermediate",
    R: "none",
    "VB/VBA": "none",
    Scala: "teach",
    Rust: "teach",
    Clojure: "teach",
    WebAssembly: "intermediate",
    Angular: "none",
    "ASP.NET": "none",
    Spring: "none",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "teach",
    Drupal: "none",
    ".NET": "intermediate",
    ".NET Core": "none",
    Pandas: "none",
    TensorFlow: "none",
    Ansible: "intermediate",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "advanced",
    Hadoop: "junior",
    "Unreal Engine": "intermediate",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "intermediate",
    Chef: "intermediate",
    CryEngine: "none",
    "Microsoft SQL Server": "intermediate",
    SQLite: "teach",
    Redis: "teach",
    MariaDB: "teach",
    Elasticsearch: "intermediate",
    Firebase: "none",
    DynamoDB: "teach",
    Cassandra: "teach",
    Linux: "teach",
    Windows: "advanced",
    AWS: "teach",
    MacOS: "advanced",
    Slack: "teach",
    "Raspberry Pi": "teach",
    WordPress: "none",
    iOS: "intermediate",
    "Google Cloud": "junior",
    Arduino: "teach",
    Kubernetes: "intermediate",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "intermediate",
    "IntelliJ IDEA": null,
    Sequelize: null,
    NHibernate: null,
    Mongoose: null,
    JOOQ: null,
    "Enterprise Javabeans": null,
    "Linq to SQL": null,
    "Entity Framework": null,
    ActiveRecord: null,
    Eclipse: null,
    "Android Studio": null,
    XCode: null,
    "Visual Studio Code": null,
    Vim: null,
    "Visual Studio": null,
    Maven: null,
    Ant: null,
    Gradle: null,
    Make: null,
    Webpack: null,
    Grunt: null,
    Gulp: null,
    Browserify: null,
    Brunch: null,
    Yarn: null,
    NPM: null,
    Bower: null,
    Yeoman: null,
    Logstash: null,
    Kibana: null,
    Splunk: null,
    SSRS: null,
    "Crystal Reports": null,
    Tableau: null,
    Vertica: null,
    Apache: null,
    Nginx: null,
    Cloudflare: null,
    IIS: null,
    LiteSpeed: null,
    Tomcat: null,
    Wildfly: null,
    Jetty: null,
    WebSphere: null,
    TFS: null,
    CVS: null,
    SVN: null,
    Mercurial: null,
    Kafka: null,
    ZeroMQ: null,
    Pulsar: null,
    MSMQ: null,
    "Cisco IOS": null,
    Arista: null,
    Cisco: null,
    Sophos: null,
    Zapier: null,
    MailChimp: null,
    HubSpot: null,
    "Google Sheets": null,
    Asana: null,
    Gmail: null,
    Twitter: null,
    "Google Calendar": null,
    "Facebook Lead Ads": null,
    Trello: null,
    "Google Drive": null,
    "Quickbooks Online": null,
    Dropbox: null,
    ActiveCampaign: null,
    Salesforce: null,
    Stripe: null,
    Shopify: null,
    WooCommerce: null,
    Kajabi: null,
    Xero: null,
    Wave: null,
    PayPal: null,
    Square: null,
    ShipStation: null,
    Discord: null,
    Outlook: null,
    Twilio: null,
    Zoom: null,
    Airtable: null,
    Teachable: null,
    Github: null,
    Gitlab: null,
    Instagram: null,
    Pinterest: null,
    Zoho: null,
    DNS: null,
    HTTP: null,
    FTP: null,
    "SMTP/POP3": null,
    NTP: null,
    TCP: null,
    UDP: null,
    SSH: null,
    Telnet: null,
    Oauth2: null,
    OIDC: null,
    SAML: null,
    HMAC: null,
    RSA: null,
    Certificates: null,
    "OWASP Top 10": null,
    "SANS Top 25": null,
    "Pen Testing": null,
    "Whitebox Testing": null,
    "Blackbox Testing": null,
    NumPy: null,
    "DOM/DHTML": null,
    Kaggle: null,
    Keras: null,
    Polymorphism: null,
    Phoenix: null,
    DigitalOcean: null,
  },
  charles: {
    "SQLAlchemy ORM": "none",
    Redux: "intermediate",
    "Vanilla JS": "teach",
    "React16 (Hooks, Context)": "advanced",
    Python: "intermediate",
    "Front End Build Tools": "junior",
    "Feature Toggles": "teach",
    "JS Testing": "advanced",
    "Python Testing": "none",
    "Production Monitoring": "intermediate",
    "UI Design": "advanced",
    "Heart & Soul": "teach",
    PostgreSQL: "junior",
    git: "advanced",
    Docker: "advanced",
    "Build Pipelines": "teach",
    Elixir: "none",
    Typescript: "none",
    Swift: "none",
    "Objective-C": "none",
    Android: "junior",
    "Apple App Store Pipeline": "intermediate",
    MongoDB: "teach",
    "Python - Flask": "none",
    "Python - Django": "none",
    "Performance Profiling": "intermediate",
    "TF - Computer vision": "junior",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "intermediate",
    "AWS S3": "teach",
    "AWS EC2": "teach",
    "AWS RDS": "teach",
    "AWS Amplify": "none",
    Netlify: "intermediate",
    Heroku: "intermediate",
    "Microsoft Azure": "advanced",
    Ruby: "intermediate",
    Erlang: "none",
    "C#": "teach",
    "Backbone/Marionette JS": "junior",
    RabbitMQ: "junior",
    "AWS Lambda": "junior",
    Webflow: "none",
    CouchDB: "junior",
    Java: "teach",
    "HTML / CSS": "teach",
    "Postman API Development": "junior",
    Node: "advanced",
    Vue: "none",
    Bootstrap: "intermediate",
    jQuery: "intermediate",
    SQL: "teach",
    "Bash/Powershell": "advanced",
    Express: "teach",
    PHP: "intermediate",
    "C++": "intermediate",
    C: "junior",
    Go: "junior",
    Assembly: "junior",
    Kotlin: "none",
    R: "junior",
    "VB/VBA": "teach",
    Scala: "none",
    Rust: "none",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "junior",
    "ASP.NET": "teach",
    Spring: "junior",
    Oracle: "junior",
    Laravel: "none",
    "Ruby on Rails": "intermediate",
    Drupal: "none",
    ".NET": "teach",
    ".NET Core": "teach",
    Pandas: "junior",
    TensorFlow: "junior",
    Ansible: "intermediate",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "intermediate",
    Hadoop: "advanced",
    "Unreal Engine": "none",
    Flutter: "none",
    "Torch/PyTorch": "junior",
    Puppet: "intermediate",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "teach",
    SQLite: "teach",
    Redis: "none",
    MariaDB: "none",
    Elasticsearch: "intermediate",
    Firebase: "none",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "advanced",
    Windows: "advanced",
    AWS: "advanced",
    MacOS: "intermediate",
    Slack: "junior",
    "Raspberry Pi": "junior",
    WordPress: "none",
    iOS: "junior",
    "Google Cloud": "junior",
    Arduino: "none",
    Kubernetes: "advanced",
    "IBM Cloud/Watson": "junior",
    "Unity Engine": "none",
    "IntelliJ IDEA": "intermediate",
    Sequelize: "teach",
    NHibernate: "junior",
    Mongoose: "teach",
    JOOQ: "advanced",
    "Enterprise Javabeans": "intermediate",
    "Linq to SQL": "advanced",
    "Entity Framework": "advanced",
    ActiveRecord: "intermediate",
    Eclipse: "intermediate",
    "Android Studio": "junior",
    XCode: "junior",
    "Visual Studio Code": "advanced",
    Vim: "intermediate",
    "Visual Studio": "advanced",
    Maven: "advanced",
    Ant: "intermediate",
    Gradle: "junior",
    Make: "junior",
    Webpack: "junior",
    Grunt: "junior",
    Gulp: "none",
    Browserify: "none",
    Brunch: "none",
    Yarn: "intermediate",
    NPM: "intermediate",
    Bower: "junior",
    Yeoman: "none",
    Logstash: "intermediate",
    Kibana: "intermediate",
    Splunk: "advanced",
    SSRS: "teach",
    "Crystal Reports": "advanced",
    Tableau: "junior",
    Vertica: "intermediate",
    Apache: "intermediate",
    Nginx: "advanced",
    Cloudflare: "none",
    IIS: "advanced",
    LiteSpeed: "none",
    Tomcat: "intermediate",
    Wildfly: "advanced",
    Jetty: "junior",
    WebSphere: "junior",
    TFS: "teach",
    CVS: "none",
    SVN: "intermediate",
    Mercurial: "none",
    Kafka: "intermediate",
    ZeroMQ: "none",
    Pulsar: "none",
    MSMQ: "intermediate",
    "Cisco IOS": "junior",
    Arista: "junior",
    Cisco: "junior",
    Sophos: "junior",
    Zapier: "advanced",
    MailChimp: "junior",
    HubSpot: "junior",
    "Google Sheets": "junior",
    Asana: "none",
    Gmail: "junior",
    Twitter: "junior",
    "Google Calendar": "none",
    "Facebook Lead Ads": "none",
    Trello: "junior",
    "Google Drive": "intermediate",
    "Quickbooks Online": "intermediate",
    Dropbox: "intermediate",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "none",
    Shopify: "junior",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "intermediate",
    Square: "junior",
    ShipStation: "intermediate",
    Discord: "none",
    Outlook: "none",
    Twilio: "intermediate",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "advanced",
    Gitlab: "none",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: "intermediate",
    HTTP: "teach",
    FTP: "advanced",
    "SMTP/POP3": "advanced",
    NTP: "intermediate",
    TCP: "intermediate",
    UDP: "intermediate",
    SSH: "intermediate",
    Telnet: "intermediate",
    Oauth2: "advanced",
    OIDC: "advanced",
    SAML: "teach",
    HMAC: "teach",
    RSA: "teach",
    Certificates: "advanced",
    "OWASP Top 10": "advanced",
    "SANS Top 25": "advanced",
    "Pen Testing": "intermediate",
    "Whitebox Testing": "advanced",
    "Blackbox Testing": "junior",
    NumPy: "junior",
    "DOM/DHTML": "advanced",
    Kaggle: "junior",
    Keras: "junior",
    Polymorphism: "teach",
    Phoenix: "none",
    DigitalOcean: "none",
  },
  kaitlyn: {
    "SQLAlchemy ORM": "none",
    Redux: "none",
    "Vanilla JS": "junior",
    "React16 (Hooks, Context)": "junior",
    Python: "junior",
    "Front End Build Tools": "junior",
    "Feature Toggles": "junior",
    "JS Testing": "junior",
    "Python Testing": "none",
    "Production Monitoring": "none",
    "UI Design": "intermediate",
    "Heart & Soul": "none",
    PostgreSQL: "junior",
    git: "junior",
    Docker: "junior",
    "Build Pipelines": "junior",
    Elixir: "junior",
    Typescript: "none",
    Swift: "junior",
    "Objective-C": "none",
    Android: "none",
    "Apple App Store Pipeline": "intermediate",
    MongoDB: "junior",
    "Python - Flask": "none",
    "Python - Django": "junior",
    "Performance Profiling": "none",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "none",
    "AWS S3": "none",
    "AWS EC2": "none",
    "AWS RDS": "none",
    "AWS Amplify": "none",
    Netlify: "junior",
    Heroku: "junior",
    "Microsoft Azure": "none",
    Ruby: "none",
    Erlang: "none",
    "C#": "junior",
    "Backbone/Marionette JS": "none",
    RabbitMQ: "none",
    "AWS Lambda": "none",
    Webflow: "none",
    CouchDB: "none",
    Java: "junior",
    "HTML / CSS": "junior",
    "Postman API Development": "junior",
    Node: "junior",
    Vue: "none",
    Bootstrap: "junior",
    jQuery: "none",
    SQL: "junior",
    "Bash/Powershell": "junior",
    Express: "junior",
    PHP: "none",
    "C++": "none",
    C: "none",
    Go: "none",
    Assembly: "none",
    Kotlin: "none",
    R: "none",
    "VB/VBA": "none",
    Scala: "none",
    Rust: "none",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "none",
    "ASP.NET": "none",
    Spring: "junior",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "none",
    Drupal: "none",
    ".NET": "none",
    ".NET Core": "none",
    Pandas: "none",
    TensorFlow: "none",
    Ansible: "none",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "none",
    Hadoop: "none",
    "Unreal Engine": "junior",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "none",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "none",
    SQLite: "junior",
    Redis: "none",
    MariaDB: "none",
    Elasticsearch: "none",
    Firebase: "none",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "none",
    Windows: "advanced",
    AWS: "none",
    MacOS: "junior",
    Slack: "intermediate",
    "Raspberry Pi": "none",
    WordPress: "junior",
    iOS: "none",
    "Google Cloud": "none",
    Arduino: "none",
    Kubernetes: "none",
    "IBM Cloud/Watson": "junior",
    "Unity Engine": "junior",
    "IntelliJ IDEA": "junior",
    Sequelize: "none",
    NHibernate: "none",
    Mongoose: "junior",
    JOOQ: "none",
    "Enterprise Javabeans": "none",
    "Linq to SQL": "none",
    "Entity Framework": "none",
    ActiveRecord: "none",
    Eclipse: "none",
    "Android Studio": "none",
    XCode: "junior",
    "Visual Studio Code": "junior",
    Vim: "junior",
    "Visual Studio": "junior",
    Maven: "none",
    Ant: "none",
    Gradle: "none",
    Make: "none",
    Webpack: "none",
    Grunt: "none",
    Gulp: "none",
    Browserify: "none",
    Brunch: "none",
    Yarn: "junior",
    NPM: "junior",
    Bower: "none",
    Yeoman: "none",
    Logstash: "none",
    Kibana: "none",
    Splunk: "none",
    SSRS: "none",
    "Crystal Reports": "none",
    Tableau: "junior",
    Vertica: "none",
    Apache: "none",
    Nginx: "none",
    Cloudflare: "none",
    IIS: "none",
    LiteSpeed: "none",
    Tomcat: "junior",
    Wildfly: "none",
    Jetty: "none",
    WebSphere: "none",
    TFS: "none",
    CVS: "none",
    SVN: "none",
    Mercurial: "none",
    Kafka: "none",
    ZeroMQ: "none",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "none",
    Arista: "none",
    Cisco: "none",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "junior",
    HubSpot: "none",
    "Google Sheets": "advanced",
    Asana: "junior",
    Gmail: "intermediate",
    Twitter: "intermediate",
    "Google Calendar": "advanced",
    "Facebook Lead Ads": "junior",
    Trello: "intermediate",
    "Google Drive": "intermediate",
    "Quickbooks Online": "junior",
    Dropbox: "junior",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "junior",
    Shopify: "junior",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "junior",
    Square: "junior",
    ShipStation: "none",
    Discord: "junior",
    Outlook: "advanced",
    Twilio: "junior",
    Zoom: "junior",
    Airtable: "intermediate",
    Teachable: "none",
    Github: "junior",
    Gitlab: "none",
    Instagram: "advanced",
    Pinterest: "intermediate",
    Zoho: "none",
    DNS: "none",
    HTTP: "junior",
    FTP: "junior",
    "SMTP/POP3": "none",
    NTP: "none",
    TCP: "none",
    UDP: "none",
    SSH: "junior",
    Telnet: "none",
    Oauth2: "none",
    OIDC: "none",
    SAML: "none",
    HMAC: "none",
    RSA: "none",
    Certificates: "none",
    "OWASP Top 10": "none",
    "SANS Top 25": "none",
    "Pen Testing": "none",
    "Whitebox Testing": "none",
    "Blackbox Testing": "none",
    NumPy: "none",
    "DOM/DHTML": "junior",
    Kaggle: "none",
    Keras: "none",
    Polymorphism: "none",
    Phoenix: null,
    DigitalOcean: null,
  },
  stajah: {
    "SQLAlchemy ORM": "none",
    Redux: "junior",
    "Vanilla JS": "intermediate",
    "React16 (Hooks, Context)": "intermediate",
    Python: "intermediate",
    "Front End Build Tools": "junior",
    "Feature Toggles": "junior",
    "JS Testing": "junior",
    "Python Testing": "junior",
    "Production Monitoring": "none",
    "UI Design": "intermediate",
    "Heart & Soul": "intermediate",
    PostgreSQL: "junior",
    git: "advanced",
    Docker: "intermediate",
    "Build Pipelines": "junior",
    Elixir: "none",
    Typescript: "junior",
    Swift: "none",
    "Objective-C": "none",
    Android: "intermediate",
    "Apple App Store Pipeline": "none",
    MongoDB: "intermediate",
    "Python - Flask": "junior",
    "Python - Django": "intermediate",
    "Performance Profiling": "none",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "none",
    "AWS S3": "none",
    "AWS EC2": "none",
    "AWS RDS": "none",
    "AWS Amplify": "none",
    Netlify: "none",
    Heroku: "none",
    "Microsoft Azure": "junior",
    Ruby: "none",
    Erlang: "none",
    "C#": "junior",
    "Backbone/Marionette JS": "none",
    RabbitMQ: "none",
    "AWS Lambda": "none",
    Webflow: "none",
    CouchDB: "none",
    Java: "junior",
    "HTML / CSS": "advanced",
    "Postman API Development": "junior",
    Node: "junior",
    Vue: "none",
    Bootstrap: "junior",
    jQuery: "none",
    SQL: "intermediate",
    "Bash/Powershell": "junior",
    Express: "junior",
    PHP: "none",
    "C++": "intermediate",
    C: "none",
    Go: "none",
    Assembly: "none",
    Kotlin: "none",
    R: "none",
    "VB/VBA": "none",
    Scala: "none",
    Rust: "none",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "intermediate",
    "ASP.NET": "none",
    Spring: "none",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "none",
    Drupal: "none",
    ".NET": "none",
    ".NET Core": "none",
    Pandas: "intermediate",
    TensorFlow: "none",
    Ansible: "none",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "none",
    Hadoop: "junior",
    "Unreal Engine": "none",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "none",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "none",
    SQLite: "junior",
    Redis: "none",
    MariaDB: "none",
    Elasticsearch: "none",
    Firebase: "intermediate",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "junior",
    Windows: "intermediate",
    AWS: "none",
    MacOS: "intermediate",
    Slack: "intermediate",
    "Raspberry Pi": "junior",
    WordPress: "junior",
    iOS: "none",
    "Google Cloud": "none",
    Arduino: "none",
    Kubernetes: "none",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "none",
    "IntelliJ IDEA": "junior",
    Sequelize: "none",
    NHibernate: "none",
    Mongoose: "junior",
    JOOQ: "none",
    "Enterprise Javabeans": "none",
    "Linq to SQL": "none",
    "Entity Framework": "none",
    ActiveRecord: "none",
    Eclipse: "none",
    "Android Studio": "intermediate",
    XCode: "junior",
    "Visual Studio Code": "intermediate",
    Vim: "none",
    "Visual Studio": "junior",
    Maven: "none",
    Ant: "none",
    Gradle: "none",
    Make: "junior",
    Webpack: "none",
    Grunt: "none",
    Gulp: "none",
    Browserify: "none",
    Brunch: "none",
    Yarn: "junior",
    NPM: "junior",
    Bower: "none",
    Yeoman: "none",
    Logstash: "none",
    Kibana: "none",
    Splunk: "none",
    SSRS: "none",
    "Crystal Reports": "none",
    Tableau: "none",
    Vertica: "none",
    Apache: "none",
    Nginx: "junior",
    Cloudflare: "none",
    IIS: "none",
    LiteSpeed: "none",
    Tomcat: "none",
    Wildfly: "none",
    Jetty: "none",
    WebSphere: "none",
    TFS: "none",
    CVS: "none",
    SVN: "none",
    Mercurial: "none",
    Kafka: "none",
    ZeroMQ: "none",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "none",
    Arista: "none",
    Cisco: "none",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "none",
    HubSpot: "none",
    "Google Sheets": "none",
    Asana: "none",
    Gmail: "none",
    Twitter: "none",
    "Google Calendar": "none",
    "Facebook Lead Ads": "none",
    Trello: "none",
    "Google Drive": "none",
    "Quickbooks Online": "none",
    Dropbox: "none",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "none",
    Shopify: "none",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "none",
    Square: "none",
    ShipStation: "none",
    Discord: "none",
    Outlook: "none",
    Twilio: "none",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "none",
    Gitlab: "none",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: "none",
    HTTP: "junior",
    FTP: "junior",
    "SMTP/POP3": "none",
    NTP: "none",
    TCP: "none",
    UDP: "none",
    SSH: "junior",
    Telnet: "none",
    Oauth2: "none",
    OIDC: "none",
    SAML: "none",
    HMAC: "none",
    RSA: "none",
    Certificates: "none",
    "OWASP Top 10": "none",
    "SANS Top 25": "none",
    "Pen Testing": "none",
    "Whitebox Testing": "none",
    "Blackbox Testing": "none",
    NumPy: "advanced",
    "DOM/DHTML": "junior",
    Kaggle: "junior",
    Keras: "none",
    Polymorphism: "intermediate",
    Phoenix: null,
    DigitalOcean: null,
  },
  taylor: {
    "SQLAlchemy ORM": "advanced",
    Redux: "teach",
    "Vanilla JS": "teach",
    "React16 (Hooks, Context)": "advanced",
    Python: "teach",
    "Front End Build Tools": "advanced",
    "Feature Toggles": "advanced",
    "JS Testing": "advanced",
    "Python Testing": "teach",
    "Production Monitoring": "intermediate",
    "UI Design": "intermediate",
    "Heart & Soul": "none",
    PostgreSQL: "advanced",
    git: "advanced",
    Docker: "advanced",
    "Build Pipelines": "intermediate",
    Elixir: "none",
    Typescript: "junior",
    Swift: "none",
    "Objective-C": "none",
    Android: "none",
    "Apple App Store Pipeline": "none",
    MongoDB: "none",
    "Python - Flask": "intermediate",
    "Python - Django": "advanced",
    "Performance Profiling": "none",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "intermediate",
    "AWS S3": "intermediate",
    "AWS EC2": "intermediate",
    "AWS RDS": "junior",
    "AWS Amplify": "junior",
    Netlify: "none",
    Heroku: "none",
    "Microsoft Azure": "none",
    Ruby: "none",
    Erlang: "none",
    "C#": "intermediate",
    "Backbone/Marionette JS": "none",
    RabbitMQ: "none",
    "AWS Lambda": "junior",
    Webflow: "none",
    CouchDB: "none",
    Java: "junior",
    "HTML / CSS": "advanced",
    "Postman API Development": "junior",
    Node: "junior",
    Vue: "none",
    Bootstrap: "intermediate",
    jQuery: "intermediate",
    SQL: "teach",
    "Bash/Powershell": "intermediate",
    Express: "junior",
    PHP: "none",
    "C++": "junior",
    C: "none",
    Go: "none",
    Assembly: "none",
    Kotlin: "none",
    R: "none",
    "VB/VBA": "none",
    Scala: "none",
    Rust: "none",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "none",
    "ASP.NET": "none",
    Spring: "none",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "none",
    Drupal: "none",
    ".NET": "junior",
    ".NET Core": "none",
    Pandas: "none",
    TensorFlow: "none",
    Ansible: "none",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "none",
    Hadoop: "none",
    "Unreal Engine": "none",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "none",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "intermediate",
    SQLite: "intermediate",
    Redis: "none",
    MariaDB: "none",
    Elasticsearch: "intermediate",
    Firebase: "none",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "junior",
    Windows: "advanced",
    AWS: "intermediate",
    MacOS: "teach",
    Slack: "advanced",
    "Raspberry Pi": "junior",
    WordPress: "junior",
    iOS: "none",
    "Google Cloud": "none",
    Arduino: "none",
    Kubernetes: "junior",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "none",
    "IntelliJ IDEA": "junior",
    Sequelize: "none",
    NHibernate: "none",
    Mongoose: "none",
    JOOQ: "none",
    "Enterprise Javabeans": "none",
    "Linq to SQL": "none",
    "Entity Framework": "none",
    ActiveRecord: "none",
    Eclipse: "junior",
    "Android Studio": "none",
    XCode: "none",
    "Visual Studio Code": "teach",
    Vim: "junior",
    "Visual Studio": "junior",
    Maven: "none",
    Ant: "none",
    Gradle: "none",
    Make: "junior",
    Webpack: "junior",
    Grunt: "none",
    Gulp: "none",
    Browserify: "none",
    Brunch: "none",
    Yarn: "intermediate",
    NPM: "intermediate",
    Bower: "none",
    Yeoman: "none",
    Logstash: "none",
    Kibana: "junior",
    Splunk: "none",
    SSRS: "none",
    "Crystal Reports": "none",
    Tableau: "none",
    Vertica: "none",
    Apache: "none",
    Nginx: "junior",
    Cloudflare: "none",
    IIS: "none",
    LiteSpeed: "none",
    Tomcat: "none",
    Wildfly: "none",
    Jetty: "none",
    WebSphere: "none",
    TFS: "junior",
    CVS: "none",
    SVN: "none",
    Mercurial: "none",
    Kafka: "none",
    ZeroMQ: "none",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "none",
    Arista: "none",
    Cisco: "none",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "junior",
    HubSpot: "none",
    "Google Sheets": "none",
    Asana: "junior",
    Gmail: "junior",
    Twitter: "junior",
    "Google Calendar": "none",
    "Facebook Lead Ads": "none",
    Trello: "none",
    "Google Drive": "none",
    "Quickbooks Online": "none",
    Dropbox: "none",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "junior",
    Shopify: "none",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "none",
    Square: "none",
    ShipStation: "none",
    Discord: "none",
    Outlook: "none",
    Twilio: "intermediate",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "advanced",
    Gitlab: "junior",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: null,
    HTTP: null,
    FTP: null,
    "SMTP/POP3": null,
    NTP: null,
    TCP: null,
    UDP: null,
    SSH: null,
    Telnet: null,
    Oauth2: null,
    OIDC: null,
    SAML: null,
    HMAC: null,
    RSA: null,
    Certificates: null,
    "OWASP Top 10": null,
    "SANS Top 25": null,
    "Pen Testing": null,
    "Whitebox Testing": null,
    "Blackbox Testing": null,
    NumPy: null,
    "DOM/DHTML": null,
    Kaggle: null,
    Keras: null,
    Polymorphism: null,
    Phoenix: null,
    DigitalOcean: null,
  },
  brian: {
    "SQLAlchemy ORM": "teach",
    Redux: "junior",
    "Vanilla JS": "teach",
    "React16 (Hooks, Context)": "advanced",
    Python: "teach",
    "Front End Build Tools": "advanced",
    "Feature Toggles": "advanced",
    "JS Testing": "advanced",
    "Python Testing": "teach",
    "Production Monitoring": "intermediate",
    "UI Design": "intermediate",
    "Heart & Soul": "none",
    PostgreSQL: "advanced",
    git: "advanced",
    Docker: "advanced",
    "Build Pipelines": "advanced",
    Elixir: "junior",
    Typescript: "junior",
    Swift: "none",
    "Objective-C": "none",
    Android: "none",
    "Apple App Store Pipeline": "none",
    MongoDB: "none",
    "Python - Flask": "teach",
    "Python - Django": "advanced",
    "Performance Profiling": "junior",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "intermediate",
    "AWS S3": "advanced",
    "AWS EC2": "intermediate",
    "AWS RDS": "intermediate",
    "AWS Amplify": "advanced",
    Netlify: "none",
    Heroku: "none",
    "Microsoft Azure": "none",
    Ruby: "none",
    Erlang: "none",
    "C#": "intermediate",
    "Backbone/Marionette JS": "advanced",
    RabbitMQ: "none",
    "AWS Lambda": "none",
    Webflow: "none",
    CouchDB: "none",
    Java: "junior",
    "HTML / CSS": "teach",
    "Postman API Development": "junior",
    Node: "intermediate",
    Vue: "none",
    Bootstrap: "intermediate",
    jQuery: "teach",
    SQL: "teach",
    "Bash/Powershell": "intermediate",
    Express: "junior",
    PHP: "none",
    "C++": "none",
    C: "none",
    Go: "none",
    Assembly: "none",
    Kotlin: "none",
    R: "none",
    "VB/VBA": "none",
    Scala: "none",
    Rust: "none",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "advanced",
    "ASP.NET": "intermediate",
    Spring: "junior",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "none",
    Drupal: "none",
    ".NET": "intermediate",
    ".NET Core": "advanced",
    Pandas: "junior",
    TensorFlow: "none",
    Ansible: "junior",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "none",
    Hadoop: "none",
    "Unreal Engine": "none",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "none",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "advanced",
    SQLite: "junior",
    Redis: "intermediate",
    MariaDB: "none",
    Elasticsearch: "intermediate",
    Firebase: "none",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "advanced",
    Windows: "intermediate",
    AWS: "intermediate",
    MacOS: "teach",
    Slack: "teach",
    "Raspberry Pi": "intermediate",
    WordPress: "none",
    iOS: "none",
    "Google Cloud": "none",
    Arduino: "none",
    Kubernetes: "junior",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "none",
    "IntelliJ IDEA": "none",
    Sequelize: "none",
    NHibernate: "none",
    Mongoose: "none",
    JOOQ: "none",
    "Enterprise Javabeans": "none",
    "Linq to SQL": "intermediate",
    "Entity Framework": "intermediate",
    ActiveRecord: "none",
    Eclipse: "none",
    "Android Studio": "junior",
    XCode: "junior",
    "Visual Studio Code": "teach",
    Vim: "intermediate",
    "Visual Studio": "advanced",
    Maven: "none",
    Ant: "none",
    Gradle: "none",
    Make: "intermediate",
    Webpack: "intermediate",
    Grunt: "none",
    Gulp: "junior",
    Browserify: "junior",
    Brunch: "junior",
    Yarn: "advanced",
    NPM: "advanced",
    Bower: "junior",
    Yeoman: "none",
    Logstash: "none",
    Kibana: "intermediate",
    Splunk: "none",
    SSRS: "junior",
    "Crystal Reports": "none",
    Tableau: "none",
    Vertica: "none",
    Apache: "junior",
    Nginx: "intermediate",
    Cloudflare: "none",
    IIS: "intermediate",
    LiteSpeed: "none",
    Tomcat: "intermediate",
    Wildfly: "none",
    Jetty: "none",
    WebSphere: "none",
    TFS: "advanced",
    CVS: "none",
    SVN: "none",
    Mercurial: "none",
    Kafka: "none",
    ZeroMQ: "none",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "none",
    Arista: "none",
    Cisco: "none",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "none",
    HubSpot: "none",
    "Google Sheets": "none",
    Asana: "junior",
    Gmail: "junior",
    Twitter: "junior",
    "Google Calendar": "junior",
    "Facebook Lead Ads": "none",
    Trello: "junior",
    "Google Drive": "junior",
    "Quickbooks Online": "none",
    Dropbox: "none",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "none",
    Shopify: "none",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "none",
    Square: "none",
    ShipStation: "none",
    Discord: "none",
    Outlook: "none",
    Twilio: "intermediate",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "junior",
    Gitlab: "none",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: "junior",
    HTTP: "intermediate",
    FTP: "intermediate",
    "SMTP/POP3": "none",
    NTP: "none",
    TCP: "junior",
    UDP: "junior",
    SSH: "junior",
    Telnet: "junior",
    Oauth2: "junior",
    OIDC: "none",
    SAML: "none",
    HMAC: "none",
    RSA: "none",
    Certificates: "intermediate",
    "OWASP Top 10": "none",
    "SANS Top 25": "none",
    "Pen Testing": "none",
    "Whitebox Testing": "none",
    "Blackbox Testing": "none",
    NumPy: "junior",
    "DOM/DHTML": "junior",
    Kaggle: "junior",
    Keras: "none",
    Polymorphism: "intermediate",
    Phoenix: "junior",
    DigitalOcean: "none",
  },
  michael: {
    "SQLAlchemy ORM": "teach",
    Redux: "intermediate",
    "Vanilla JS": "advanced",
    "React16 (Hooks, Context)": "advanced",
    Python: "teach",
    "Front End Build Tools": "intermediate",
    "Feature Toggles": "advanced",
    "JS Testing": "intermediate",
    "Python Testing": "advanced",
    "Production Monitoring": "advanced",
    "UI Design": "advanced",
    "Heart & Soul": "intermediate",
    PostgreSQL: "teach",
    git: "advanced",
    Docker: "advanced",
    "Build Pipelines": "intermediate",
    Elixir: "none",
    Typescript: "intermediate",
    Swift: "none",
    "Objective-C": "none",
    Android: "none",
    "Apple App Store Pipeline": "none",
    MongoDB: "intermediate",
    "Python - Flask": "teach",
    "Python - Django": "advanced",
    "Performance Profiling": "advanced",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "intermediate",
    "AWS S3": "junior",
    "AWS EC2": "junior",
    "AWS RDS": "junior",
    "AWS Amplify": "none",
    Netlify: "intermediate",
    Heroku: "junior",
    "Microsoft Azure": "junior",
    Ruby: "junior",
    Erlang: "none",
    "C#": "none",
    "Backbone/Marionette JS": "none",
    RabbitMQ: "intermediate",
    "AWS Lambda": "junior",
    Webflow: "none",
    CouchDB: "none",
    Java: "teach",
    "HTML / CSS": "advanced",
    "Postman API Development": "none",
    Node: "advanced",
    Vue: "junior",
    Bootstrap: "intermediate",
    jQuery: "none",
    SQL: "advanced",
    "Bash/Powershell": "advanced",
    Express: "advanced",
    PHP: "junior",
    "C++": "none",
    C: "none",
    Go: "junior",
    Assembly: "none",
    Kotlin: "junior",
    R: "none",
    "VB/VBA": "none",
    Scala: "junior",
    Rust: "none",
    Clojure: "intermediate",
    WebAssembly: "none",
    Angular: "none",
    "ASP.NET": "none",
    Spring: "junior",
    Oracle: "advanced",
    Laravel: "none",
    "Ruby on Rails": "junior",
    Drupal: "junior",
    ".NET": "none",
    ".NET Core": "none",
    Pandas: "junior",
    TensorFlow: "none",
    Ansible: "none",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "junior",
    Hadoop: "junior",
    "Unreal Engine": "none",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "none",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "intermediate",
    SQLite: "advanced",
    Redis: "intermediate",
    MariaDB: "advanced",
    Elasticsearch: "junior",
    Firebase: "none",
    DynamoDB: "junior",
    Cassandra: "none",
    Linux: "teach",
    Windows: "junior",
    AWS: "junior",
    MacOS: "intermediate",
    Slack: "intermediate",
    "Raspberry Pi": "advanced",
    WordPress: "junior",
    iOS: "none",
    "Google Cloud": "junior",
    Arduino: "none",
    Kubernetes: "junior",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "none",
    "IntelliJ IDEA": "junior",
    Sequelize: "intermediate",
    NHibernate: "junior",
    Mongoose: "advanced",
    JOOQ: "none",
    "Enterprise Javabeans": "intermediate",
    "Linq to SQL": "none",
    "Entity Framework": "none",
    ActiveRecord: "none",
    Eclipse: "intermediate",
    "Android Studio": "none",
    XCode: "none",
    "Visual Studio Code": "advanced",
    Vim: "teach",
    "Visual Studio": "none",
    Maven: "intermediate",
    Ant: "advanced",
    Gradle: "intermediate",
    Make: "junior",
    Webpack: "none",
    Grunt: "none",
    Gulp: "none",
    Browserify: "none",
    Brunch: "none",
    Yarn: "intermediate",
    NPM: "intermediate",
    Bower: "none",
    Yeoman: "none",
    Logstash: "junior",
    Kibana: "intermediate",
    Splunk: "junior",
    SSRS: "none",
    "Crystal Reports": "none",
    Tableau: "none",
    Vertica: "none",
    Apache: "junior",
    Nginx: "intermediate",
    Cloudflare: "none",
    IIS: "none",
    LiteSpeed: "none",
    Tomcat: "intermediate",
    Wildfly: "none",
    Jetty: "junior",
    WebSphere: "none",
    TFS: "none",
    CVS: "junior",
    SVN: "intermediate",
    Mercurial: "intermediate",
    Kafka: "none",
    ZeroMQ: "junior",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "none",
    Arista: "none",
    Cisco: "none",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "junior",
    HubSpot: "none",
    "Google Sheets": "junior",
    Asana: "junior",
    Gmail: "junior",
    Twitter: "intermediate",
    "Google Calendar": "junior",
    "Facebook Lead Ads": "junior",
    Trello: "none",
    "Google Drive": "none",
    "Quickbooks Online": "none",
    Dropbox: "junior",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "none",
    Shopify: "none",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "none",
    Square: "none",
    ShipStation: "none",
    Discord: "none",
    Outlook: "none",
    Twilio: "intermediate",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "junior",
    Gitlab: "none",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: "intermediate",
    HTTP: "advanced",
    FTP: "intermediate",
    "SMTP/POP3": "junior",
    NTP: "junior",
    TCP: "intermediate",
    UDP: "intermediate",
    SSH: "junior",
    Telnet: "none",
    Oauth2: "none",
    OIDC: "none",
    SAML: "none",
    HMAC: "none",
    RSA: "none",
    Certificates: "none",
    "OWASP Top 10": "none",
    "SANS Top 25": "none",
    "Pen Testing": "none",
    "Whitebox Testing": "none",
    "Blackbox Testing": "none",
    NumPy: "junior",
    "DOM/DHTML": "junior",
    Kaggle: "none",
    Keras: "none",
    Polymorphism: "advanced",
    Phoenix: "none",
    DigitalOcean: "none",
  },
  sam: {
    "SQLAlchemy ORM": "intermediate",
    Redux: "advanced",
    "Vanilla JS": "teach",
    "React16 (Hooks, Context)": "advanced",
    Python: "advanced",
    "Front End Build Tools": "advanced",
    "Feature Toggles": "intermediate",
    "JS Testing": "advanced",
    "Python Testing": "intermediate",
    "Production Monitoring": "junior",
    "UI Design": "junior",
    "Heart & Soul": "none",
    PostgreSQL: "intermediate",
    git: "teach",
    Docker: "advanced",
    "Build Pipelines": "intermediate",
    Elixir: "intermediate",
    Typescript: "junior",
    Swift: "junior",
    "Objective-C": "none",
    Android: "junior",
    "Apple App Store Pipeline": "none",
    MongoDB: "intermediate",
    "Python - Flask": "intermediate",
    "Python - Django": "advanced",
    "Performance Profiling": "intermediate",
    "TF - Computer vision": "none",
    "TF - Time Series Modeling": "none",
    "TF - NLP": "none",
    "React Native": "none",
    "AWS S3": "junior",
    "AWS EC2": "intermediate",
    "AWS RDS": "none",
    "AWS Amplify": "none",
    Netlify: "intermediate",
    Heroku: "junior",
    "Microsoft Azure": "junior",
    Ruby: "intermediate",
    Erlang: "advanced",
    "C#": "none",
    "Backbone/Marionette JS": "junior",
    RabbitMQ: "intermediate",
    "AWS Lambda": "junior",
    Webflow: "none",
    CouchDB: "intermediate",
    Java: "junior",
    "HTML / CSS": "advanced",
    "Postman API Development": "junior",
    Node: "intermediate",
    Vue: "none",
    Bootstrap: "junior",
    jQuery: "intermediate",
    SQL: "intermediate",
    "Bash/Powershell": "intermediate",
    Express: "intermediate",
    PHP: "none",
    "C++": "junior",
    C: "none",
    Go: "none",
    Assembly: "none",
    Kotlin: "none",
    R: "junior",
    "VB/VBA": "none",
    Scala: "none",
    Rust: "none",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "junior",
    "ASP.NET": "none",
    Spring: "junior",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "intermediate",
    Drupal: "none",
    ".NET": "none",
    ".NET Core": "none",
    Pandas: "none",
    TensorFlow: "none",
    Ansible: "junior",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "none",
    Hadoop: "none",
    "Unreal Engine": "none",
    Flutter: "junior",
    "Torch/PyTorch": "none",
    Puppet: "none",
    Chef: "none",
    CryEngine: "none",
    "Microsoft SQL Server": "intermediate",
    SQLite: "intermediate",
    Redis: "junior",
    MariaDB: "none",
    Elasticsearch: "intermediate",
    Firebase: "junior",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "intermediate",
    Windows: "junior",
    AWS: "junior",
    MacOS: "teach",
    Slack: "advanced",
    "Raspberry Pi": "junior",
    WordPress: "junior",
    iOS: "junior",
    "Google Cloud": "junior",
    Arduino: "junior",
    Kubernetes: "junior",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "none",
    "IntelliJ IDEA": "junior",
    Sequelize: "intermediate",
    NHibernate: "none",
    Mongoose: "intermediate",
    JOOQ: "junior",
    "Enterprise Javabeans": "none",
    "Linq to SQL": "none",
    "Entity Framework": "none",
    ActiveRecord: "advanced",
    Eclipse: "junior",
    "Android Studio": "junior",
    XCode: "none",
    "Visual Studio Code": "advanced",
    Vim: "intermediate",
    "Visual Studio": "junior",
    Maven: "junior",
    Ant: "none",
    Gradle: "none",
    Make: "junior",
    Webpack: "advanced",
    Grunt: "intermediate",
    Gulp: "intermediate",
    Browserify: "junior",
    Brunch: "none",
    Yarn: "intermediate",
    NPM: "intermediate",
    Bower: "junior",
    Yeoman: "junior",
    Logstash: "none",
    Kibana: "junior",
    Splunk: "none",
    SSRS: "none",
    "Crystal Reports": "none",
    Tableau: "none",
    Vertica: "none",
    Apache: "junior",
    Nginx: "junior",
    Cloudflare: "none",
    IIS: "none",
    LiteSpeed: "none",
    Tomcat: "junior",
    Wildfly: "none",
    Jetty: "none",
    WebSphere: "none",
    TFS: "none",
    CVS: "none",
    SVN: "none",
    Mercurial: "none",
    Kafka: "none",
    ZeroMQ: "junior",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "none",
    Arista: "none",
    Cisco: "none",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "junior",
    HubSpot: "none",
    "Google Sheets": "none",
    Asana: "junior",
    Gmail: "junior",
    Twitter: "junior",
    "Google Calendar": "none",
    "Facebook Lead Ads": "none",
    Trello: "none",
    "Google Drive": "none",
    "Quickbooks Online": "none",
    Dropbox: "none",
    ActiveCampaign: "none",
    Salesforce: "none",
    Stripe: "junior",
    Shopify: "none",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "none",
    Square: "none",
    ShipStation: "none",
    Discord: "none",
    Outlook: "junior",
    Twilio: "intermediate",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "advanced",
    Gitlab: "junior",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: "junior",
    HTTP: "junior",
    FTP: "junior",
    "SMTP/POP3": "none",
    NTP: "none",
    TCP: "junior",
    UDP: "none",
    SSH: "junior",
    Telnet: "none",
    Oauth2: "intermediate",
    OIDC: "none",
    SAML: "none",
    HMAC: "none",
    RSA: "intermediate",
    Certificates: "intermediate",
    "OWASP Top 10": "intermediate",
    "SANS Top 25": "none",
    "Pen Testing": "junior",
    "Whitebox Testing": "none",
    "Blackbox Testing": "junior",
    NumPy: "none",
    "DOM/DHTML": "advanced",
    Kaggle: "none",
    Keras: "none",
    Polymorphism: "teach",
    Phoenix: "advanced",
    DigitalOcean: "junior",
  },
  chris: {
    "SQLAlchemy ORM": "intermediate",
    Redux: "junior",
    "Vanilla JS": "intermediate",
    "React16 (Hooks, Context)": "junior",
    Python: "teach",
    "Front End Build Tools": "junior",
    "Feature Toggles": "intermediate",
    "JS Testing": "intermediate",
    "Python Testing": "teach",
    "Production Monitoring": "intermediate",
    "UI Design": "intermediate",
    "Heart & Soul": "none",
    PostgreSQL: "advanced",
    git: "teach",
    Docker: "advanced",
    "Build Pipelines": "advanced",
    Elixir: "advanced",
    Typescript: "junior",
    Swift: "intermediate",
    "Objective-C": "intermediate",
    Android: "junior",
    "Apple App Store Pipeline": "intermediate",
    MongoDB: "junior",
    "Python - Flask": "intermediate",
    "Python - Django": "junior",
    "Performance Profiling": "advanced",
    "TF - Computer vision": "teach",
    "TF - Time Series Modeling": "intermediate",
    "TF - NLP": "intermediate",
    "React Native": "junior",
    "AWS S3": "intermediate",
    "AWS EC2": "intermediate",
    "AWS RDS": "intermediate",
    "AWS Amplify": "intermediate",
    Netlify: "intermediate",
    Heroku: "intermediate",
    "Microsoft Azure": "junior",
    Ruby: "advanced",
    Erlang: "intermediate",
    "C#": "junior",
    "Backbone/Marionette JS": "none",
    RabbitMQ: "junior",
    "AWS Lambda": "intermediate",
    Webflow: "none",
    CouchDB: "none",
    Java: "none",
    "HTML / CSS": "advanced",
    "Postman API Development": "intermediate",
    Node: "intermediate",
    Vue: "none",
    Bootstrap: "intermediate",
    jQuery: "intermediate",
    SQL: "teach",
    "Bash/Powershell": "teach",
    Express: "intermediate",
    PHP: "junior",
    "C++": "intermediate",
    C: "advanced",
    Go: "junior",
    Assembly: "junior",
    Kotlin: "none",
    R: "junior",
    "VB/VBA": "none",
    Scala: "none",
    Rust: "junior",
    Clojure: "none",
    WebAssembly: "none",
    Angular: "none",
    "ASP.NET": "none",
    Spring: "none",
    Oracle: "none",
    Laravel: "none",
    "Ruby on Rails": "teach",
    Drupal: "none",
    ".NET": "none",
    ".NET Core": "none",
    Pandas: "advanced",
    TensorFlow: "advanced",
    Ansible: "junior",
    Cordova: "none",
    Xamarin: "none",
    "Apache Spark": "none",
    Hadoop: "none",
    "Unreal Engine": "none",
    Flutter: "none",
    "Torch/PyTorch": "none",
    Puppet: "junior",
    Chef: "junior",
    CryEngine: "none",
    "Microsoft SQL Server": "junior",
    SQLite: "intermediate",
    Redis: "junior",
    MariaDB: "none",
    Elasticsearch: "junior",
    Firebase: "junior",
    DynamoDB: "none",
    Cassandra: "none",
    Linux: "teach",
    Windows: "intermediate",
    AWS: "intermediate",
    MacOS: "teach",
    Slack: "advanced",
    "Raspberry Pi": "advanced",
    WordPress: "intermediate",
    iOS: "intermediate",
    "Google Cloud": "junior",
    Arduino: "junior",
    Kubernetes: "intermediate",
    "IBM Cloud/Watson": "none",
    "Unity Engine": "none",
    "IntelliJ IDEA": "none",
    Sequelize: "none",
    NHibernate: "none",
    Mongoose: "junior",
    JOOQ: "none",
    "Enterprise Javabeans": "none",
    "Linq to SQL": "none",
    "Entity Framework": "none",
    ActiveRecord: "advanced",
    Eclipse: "none",
    "Android Studio": "none",
    XCode: "intermediate",
    "Visual Studio Code": "advanced",
    Vim: "advanced",
    "Visual Studio": "none",
    Maven: "none",
    Ant: "none",
    Gradle: "junior",
    Make: "teach",
    Webpack: "intermediate",
    Grunt: "none",
    Gulp: "none",
    Browserify: "none",
    Brunch: "intermediate",
    Yarn: "intermediate",
    NPM: "intermediate",
    Bower: "none",
    Yeoman: "junior",
    Logstash: "none",
    Kibana: "none",
    Splunk: "none",
    SSRS: "none",
    "Crystal Reports": "none",
    Tableau: "none",
    Vertica: "none",
    Apache: "intermediate",
    Nginx: "intermediate",
    Cloudflare: "none",
    IIS: "none",
    LiteSpeed: "none",
    Tomcat: "none",
    Wildfly: "none",
    Jetty: "none",
    WebSphere: "none",
    TFS: "none",
    CVS: "junior",
    SVN: "intermediate",
    Mercurial: "junior",
    Kafka: "junior",
    ZeroMQ: "junior",
    Pulsar: "none",
    MSMQ: "none",
    "Cisco IOS": "junior",
    Arista: "none",
    Cisco: "intermediate",
    Sophos: "none",
    Zapier: "none",
    MailChimp: "junior",
    HubSpot: "none",
    "Google Sheets": "junior",
    Asana: "junior",
    Gmail: "junior",
    Twitter: "junior",
    "Google Calendar": "junior",
    "Facebook Lead Ads": "none",
    Trello: "junior",
    "Google Drive": "junior",
    "Quickbooks Online": "none",
    Dropbox: "junior",
    ActiveCampaign: "none",
    Salesforce: "junior",
    Stripe: "junior",
    Shopify: "none",
    WooCommerce: "none",
    Kajabi: "none",
    Xero: "none",
    Wave: "none",
    PayPal: "junior",
    Square: "junior",
    ShipStation: "none",
    Discord: "none",
    Outlook: "none",
    Twilio: "junior",
    Zoom: "none",
    Airtable: "none",
    Teachable: "none",
    Github: "advanced",
    Gitlab: "junior",
    Instagram: "none",
    Pinterest: "none",
    Zoho: "none",
    DNS: "intermediate",
    HTTP: "intermediate",
    FTP: "intermediate",
    "SMTP/POP3": "intermediate",
    NTP: "junior",
    TCP: "junior",
    UDP: "junior",
    SSH: "intermediate",
    Telnet: "junior",
    Oauth2: "junior",
    OIDC: "junior",
    SAML: "junior",
    HMAC: "none",
    RSA: "none",
    Certificates: "intermediate",
    "OWASP Top 10": "none",
    "SANS Top 25": "none",
    "Pen Testing": "none",
    "Whitebox Testing": "none",
    "Blackbox Testing": "none",
    NumPy: "advanced",
    "DOM/DHTML": "intermediate",
    Kaggle: "intermediate",
    Keras: "junior",
    Polymorphism: "intermediate",
    Phoenix: "teach",
    DigitalOcean: "advanced",
  },
};
