export const technologies = [
  "SQLAlchemy ORM",
  "Redux",
  "Vanilla JS",
  "React16 (Hooks, Context)",
  "Python",
  "Front End Build Tools",
  "Feature Toggles",
  "JS Testing",
  "Python Testing",
  "Production Monitoring",
  "UI Design",
  "Heart & Soul",
  "PostgreSQL",
  "git",
  "Docker",
  "Build Pipelines",
  "Elixir",
  "Typescript",
  "Swift",
  "Objective-C",
  "Android",
  "Apple App Store Pipeline",
  "MongoDB",
  "Python - Flask",
  "Python - Django",
  "Performance Profiling",
  "TF - Computer vision",
  "TF - Time Series Modeling",
  "TF - Natural Language Processing",
  "React Native",
  "AWS S3",
  "AWS EC2",
  "AWS RDS",
  "AWS Amplify",
  "Netlify",
  "Heroku",
  "Microsoft Azure",
  "Ruby",
  "Erlang",
  "C#",
  "Backbone/Marionette JS",
  "RabbitMQ",
  "AWS Lambda",
  "Webflow",
  "CouchDB",
  "Java",
  "HTML / CSS",
  "Postman API Development",
  "Node",
  "Vue",
  "Bootstrap",
  "jQuery",
  "SQL",
  "Bash/Powershell",
  "Express",
  "PHP",
  "C++",
  "C",
  "Go",
  "Assembly",
  "Kotlin",
  "R",
  "VB/VBA",
  "Scala",
  "Rust",
  "Clojure",
  "WebAssembly",
  "Angular",
  "ASP.NET",
  "Spring",
  "Oracle",
  "Laravel",
  "Ruby on Rails",
  "Drupal",
  ".NET",
  ".NET Core",
  "Pandas",
  "TensorFlow",
  "Ansible",
  "Cordova",
  "Xamarin",
  "Apache Spark",
  "Hadoop",
  "Unreal Engine",
  "Flutter",
  "Torch/PyTorch",
  "Puppet",
  "Chef",
  "CryEngine",
  "Microsoft SQL Server",
  "SQLite",
  "Redis",
  "MariaDB",
  "Elasticsearch",
  "Firebase",
  "DynamoDB",
  "Cassandra",
  "Linux",
  "Windows",
  "AWS",
  "MacOS",
  "Slack",
  "Raspberry Pi",
  "WordPress",
  "iOS",
  "Google Cloud",
  "Arduino",
  "Kubernetes",
  "IBM Cloud/Watson",
  "Unity Engine",
  "IntelliJ IDEA",
  "Sequelize",
  "NHibernate",
  "Mongoose",
  "JOOQ",
  "Enterprise Javabeans",
  "Linq to SQL",
  "Entity Framework",
  "ActiveRecord",
  "Eclipse",
  "Android Studio",
  "XCode",
  "Visual Studio Code",
  "Vim",
  "Visual Studio",
  "Maven",
  "Ant",
  "Gradle",
  "Make",
  "Webpack",
  "Grunt",
  "Gulp",
  "Browserify",
  "Brunch",
  "Yarn",
  "NPM",
  "Bower",
  "Yeoman",
  "Logstash",
  "Kibana",
  "Splunk",
  "SSRS",
  "Crystal Reports",
  "Tableau",
  "Vertica",
  "Apache",
  "Nginx",
  "Cloudflare",
  "IIS",
  "LiteSpeed",
  "Tomcat",
  "Wildfly",
  "Jetty",
  "WebSphere",
  "TFS",
  "CVS",
  "SVN",
  "Mercurial",
  "Kafka",
  "ZeroMQ",
  "Pulsar",
  "MSMQ",
  "Cisco IOS",
  "Arista",
  "Cisco",
  "Sophos",
  "Zapier",
  "MailChimp",
  "HubSpot",
  "Google Sheets",
  "Asana",
  "Gmail",
  "Twitter",
  "Google Calendar",
  "Facebook Lead Ads",
  "Trello",
  "Google Drive",
  "Quickbooks Online",
  "Dropbox",
  "ActiveCampaign",
  "Salesforce",
  "Stripe",
  "Shopify",
  "WooCommerce",
  "Kajabi",
  "Xero",
  "Wave",
  "PayPal",
  "Square",
  "ShipStation",
  "Discord",
  "Outlook",
  "Twilio",
  "Zoom",
  "Airtable",
  "Teachable",
  "Github",
  "Gitlab",
  "Instagram",
  "Pinterest",
  "Zoho",
  "DNS",
  "HTTP",
  "FTP",
  "SMTP/POP3",
  "NTP",
  "TCP",
  "UDP",
  "SSH",
  "Telnet",
  "Oauth2",
  "OIDC",
  "SAML",
  "HMAC",
  "RSA",
  "Certificates",
  "OWASP Top 10",
  "SANS Top 25",
  "Pen Testing",
  "Whitebox Testing",
  "Blackbox Testing",
  "NumPy",
  "DOM/DHTML",
  "Kaggle",
  "Keras",
  "Polymorphism",
  "Phoenix",
  "DigitalOcean",
];
